version: '3.8'

services:
  # Backend FastAPI (usa SQLite en /data/hotel_reservas.db)
  backend:
    build: .
    container_name: hotel_backend
    environment:
      DATABASE_URL: sqlite:////data/hotel_reservas.db
      WEATHER_API_KEY: ${WEATHER_API_KEY:-demo_key}
    ports:
      - "8000:8000"
    volumes:
      - app_db:/data              # volumen para persistir el archivo .db
      - ./pipeline/logs:/app/pipeline/logs
      - ./pipeline/backups:/app/pipeline/backups
      - ./frontend:/frontend:ro
    networks:
      - hotel_network

  # Servidor web (sirve frontend y hace proxy a /api → backend)
  frontend:
    image: nginx:alpine
    container_name: hotel_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - hotel_network

  # Prefect (opcional, UI en http://localhost:4200)
  prefect:
    image: prefecthq/prefect:2.14.16-python3.12
    container_name: hotel_prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ./pipeline:/app/pipeline
    networks:
      - hotel_network

volumes:
  app_db:

networks:
  hotel_network:
    driver: bridge
